package com.rr.anno;
// Generated 2017-10-20 18:31:36 by Hibernate Tools 4.3.1.Final

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "ao")
public class Resource implements java.io.Serializable {

	private Integer resid;
	private String resname;
	private Integer partend;
	private String url;
	private Set<Resourcerole> resourceroles;

	public Resource() {
	}

	public Resource(String resname) {
		this.resname = resname;
	}

	public Resource(String resname, Integer partend, String url, Set<Resourcerole> resourceroles) {
		this.resname = resname;
		this.partend = partend;
		this.url = url;
		this.resourceroles = resourceroles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "resid", unique = true, nullable = false)
	public Integer getResid() {
		return this.resid;
	}

	public void setResid(Integer resid) {
		this.resid = resid;
	}

	@Column(name = "resname", nullable = false, length = 30)
	public String getResname() {
		return this.resname;
	}

	public void setResname(String resname) {
		this.resname = resname;
	}

	@Column(name = "partend")
	public Integer getPartend() {
		return this.partend;
	}

	public void setPartend(Integer partend) {
		this.partend = partend;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<Resourcerole> getResourceroles() {
		return this.resourceroles;
	}

	public void setResourceroles(Set<Resourcerole> resourceroles) {
		this.resourceroles = resourceroles;
	}

}
