package com.rr.anno;
// Generated 2017-10-20 18:31:36 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resourcerole generated by hbm2java
 */
@Entity
@Table(name = "resourcerole", catalog = "ao")
public class Resourcerole implements java.io.Serializable {

	private Integer rrid;
	private Resource resource;
	private Role role;

	public Resourcerole() {
	}

	public Resourcerole(Resource resource, Role role) {
		this.resource = resource;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rrid", unique = true, nullable = false)
	public Integer getRrid() {
		return this.rrid;
	}

	public void setRrid(Integer rrid) {
		this.rrid = rrid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resid", nullable = false)
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rid", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
