package com.rr.anno;
// Generated 2017-10-20 18:31:36 by Hibernate Tools 4.3.1.Final

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "ao")
public class Role implements java.io.Serializable {

	private Integer rid;
	private String rname;
	private Set<Resourcerole> resourceroles;
	private Set<Userrole> userroles;

	public Role() {
	}

	public Role(String rname) {
		this.rname = rname;
	}

	public Role(String rname, Set<Resourcerole> resourceroles, Set<Userrole> userroles) {
		this.rname = rname;
		this.resourceroles = resourceroles;
		this.userroles = userroles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rid", unique = true, nullable = false)
	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	@Column(name = "rname", nullable = false, length = 30)
	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Resourcerole> getResourceroles() {
		return this.resourceroles;
	}

	public void setResourceroles(Set<Resourcerole> resourceroles) {
		this.resourceroles = resourceroles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Userrole> getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Set<Userrole> userroles) {
		this.userroles = userroles;
	}

}
