package com.rr.anno;
// Generated 2017-10-20 18:31:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "ao")
public class User implements java.io.Serializable {

	private Integer uid;
	private Department department;
	private String uname;
	private String unumber;
	private String password;
	private String sex;
	private String phone;
	private String email;
	private Set<Userrole> userroles;

	public User() {
	}

	public User(Department department, String uname, String unumber, String password, String sex, String email) {
		this.department = department;
		this.uname = uname;
		this.unumber = unumber;
		this.password = password;
		this.sex = sex;
		this.email = email;
	}

	public User(Department department, String uname, String unumber, String password, String sex, String phone,
			String email, Set<Userrole> userroles) {
		this.department = department;
		this.uname = uname;
		this.unumber = unumber;
		this.password = password;
		this.sex = sex;
		this.phone = phone;
		this.email = email;
		this.userroles = userroles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "did", nullable = false)
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Column(name = "uname", nullable = false, length = 30)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "unumber", nullable = false, length = 30)
	public String getUnumber() {
		return this.unumber;
	}

	public void setUnumber(String unumber) {
		this.unumber = unumber;
	}

	@Column(name = "password", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "sex", nullable = false, length = 10)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "phone", length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Userrole> getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Set<Userrole> userroles) {
		this.userroles = userroles;
	}
	

}
